apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: cadvisor
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.45.0
  name: cadvisor
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: cadvisor
    app.kubernetes.io/part-of: kube-prometheus
